#!/command/with-contenv sh

# Set nginx folder permission
# chown -R ${UNAME}:${GNAME} /usr/local/nginx
# Create nginx.pid if missing
if [ ! -f "/var/run/nginx.pid" ];
then
  touch /var/run/nginx.pid
fi
# set pid permission
setgroup /var/run/nginx.pid

# Executables
setgroup /etc/nginx
setgroup /usr/local/nginx

# for i in /var/log/nginx /${NGINX_WEBROOT} ${NGINX_WEBROOT}/defaults/acme-challenge ${NGINX_WEBROOT}/defaults/error ${NGINX_WEBROOT}/defaults/filelist /etc/nginx/certificates /etc/nginx /etc/nginx/sites.d /etc/nginx/templates /tmp/modsecurity/data /tmp/modsecurity/upload /tmp/modsecurity/tmp /var/log/nginx/modsecuriy

#/etc/nginx /etc/nginx/sites.d /etc/nginx/maxmind /etc/nginx/templates
# for i in /var/log/nginx ${NGINX_WEBROOT} ${NGINX_WEBROOT}/defaults/error ${NGINX_WEBROOT}/defaults/filelist /tmp/modsecurity/data /tmp/modsecurity/upload /tmp/modsecurity/tmp /var/log/nginx/modsecuriy


for i in /app/acme /templates ${MAXMIND_PATH} ${MODSEC_AUDIT_STORAGE} ${MODSEC_DATA_DIR} ${MODSEC_TMP_DIR} ${MODSEC_UPLOAD_DIR} ${NGINX_CACHE_DIR} ${NGINX_CERT_PATH} ${NGINX_WEBROOT} /var/log/nginx /scripts 
do
  if [ ! -d "${i}" ]
  then
    echo "Create directory ${i}"
    mkdir -p ${i}
  fi
  echo "Ensuring ownership for ${i}"
  setgroup ${i}
done