name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug", "triage"]
# assignees:
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is this a new issue?
      description: Please search to see if this issue is already reported.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: current-behaviour
    attributes:
      label: Current Behaviour
      description: Explain what the current behaviour is
      placeholder: Tell us what you see!
      # value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: What is actually expected to happen?
      placeholder: What do you expect to see?
      # value: "A bug happened!"
    validations:
      required: false
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: How did we reproduce this?
      placeholder: Explain how we can reproduce this issue?
      # value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: container-config
    attributes:
      label: Container Config
      description: What is the container config?
      placeholder: Mention the ENV variables, or arguments used to build (if custom) etc
      # value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: container-logs
    attributes:
      label: Logs
      description: Container Logs
      placeholder: Paste the output of logs. You can fetch this by running docker log <container-name>
      # value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Mention the environment
      placeholder: Mention operating system, docker version etc.
      # value: "A bug happened!"
    validations:
      required: false
