# Default modsecurity config
Include /etc/nginx/modsecurity/modsecurity.conf
# For each site or location, you can create an override and load it
Include /etc/nginx/modsecurity/rules.d/some_rule.conf
# Or
SecRule ARGS:testparam "@contains test" "id:1234,deny,log,status:403"