# https://github.com/Lax/traffic-accounting-nginx-module
# Ensure module is loaded
# load_module modules/ngx_http_accounting_module.so;
accounting on;
accounting_id $hostname;
accounting_log /var/log/nginx/$hostname/accounting.log;
accounting_interval 60;
accounting_perturb on;
# Change accounting id where need be
