#!/bin/sh
ACME_CERT_PATH=/acme/certs
DEBUG_MODE=false

error() {
    echo "Error: $1"
    if [ -f /var/logs/nginx/acmeRenew.run ]; then
        rm -f /var/logs/nginx/acmeRenew.run
    fi
    exit 1
}
debug() {
    if [ "$DEBUG_MODE" = "true" ]; then
    echo "Debug: $1"
  fi
}

info() {
    echo "$@"
}

moveCertificates() {
    BACKUP_DATE=$(date +%Y-%m-%d)
    # Loop through directories in ACME_CERT_PATH and move certificates to /etc/nginx/certs
    for dir in $ACME_CERT_PATH; do
        if [ -d $DIR ]; then
            DOMAIN=${DIR//_ecc/}
            # Move existing
            if [ -f /etc/nginx/certs/$DOMAIN.crt ]; then
                mv /etc/nginx/certs/$DOMAIN.crt /etc/nginx/certs/$DOMAIN.crt.${BACKUP_DATE}
            fi
            if [ -f /etc/nginx/certs/$DOMAIN.key ]; then
                mv /etc/nginx/certs/$DOMAIN.key /etc/nginx/certs/$DOMAIN.key.${BACKUP_DATE}
            fi
            cp $DIR/fullchain.cer /etc/nginx/certs/$DOMAIN.crt
            cp $DIR/$DOMAIN.key /etc/nginx/certs/$DOMAIN.key
        fi
    done;
}

while [ -f /var/logs/nginx/acmeRenew.run ]; do
    info "Renew process is already running. Skipping"
    exit 0
done

touch /var/logs/nginx/acmeRenew.run
# Call renew method
acme --renew-all
# Check if error occured
if [ $? -ne 0 ]; then
    error "Renew process failed"
fi

moveCertificates

if [ $? -ne 0 ]; then
    error "Could not move certificates to the correct location"
fi
rm -f /var/logs/nginx/acmeRenew.run

# Reload nginx

exit 0