#!/command/with-contenv sh
if [ ! -z ${MAXMIND_KEY} ]
then
  for template in 'maxmind-city.conf' 'maxmind-country.conf'
  do
    echo "[info] Removing template ${template}"
    rm /etc/nginx/defaults/${template}
  done
fi

echo "[info] Removing default site config"
rm /etc/nginx/sites.d/0-default.conf